server:
  port: 8080

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "cinema-db"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"

admin:
  key: ""
